# Generated by Django 5.2.5 on 2025-09-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_brand_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_logo',
            field=models.FileField(upload_to='brands/'),
        ),
    ]
