# Generated by Django 5.2.5 on 2025-09-17 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_image_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_year', models.PositiveIntegerField()),
                ('network_type', models.CharField(max_length=50)),
                ('battery', models.PositiveIntegerField(help_text='mAh')),
                ('screen_size', models.DecimalField(decimal_places=2, help_text='inches', max_digits=4)),
                ('screen_type', models.CharField(blank=True, max_length=50, null=True)),
                ('resolution', models.CharField(blank=True, max_length=20, null=True)),
                ('colors', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, help_text='grams', null=True)),
                ('dimensions', models.CharField(blank=True, max_length=50, null=True)),
                ('sim_type', models.CharField(blank=True, max_length=20, null=True)),
                ('sim_slots', models.PositiveIntegerField(default=1)),
                ('memory_internal', models.CharField(blank=True, max_length=50, null=True)),
                ('memory_card_support', models.BooleanField(default=False)),
                ('has_sms', models.BooleanField(default=True)),
                ('has_mms', models.BooleanField(default=False)),
                ('has_infrared', models.BooleanField(default=False)),
                ('has_bluetooth', models.BooleanField(default=False)),
                ('has_wap', models.BooleanField(default=False)),
                ('has_gprs', models.BooleanField(default=False)),
                ('has_camera', models.BooleanField(default=False)),
                ('has_radio', models.BooleanField(default=False)),
                ('has_mp3', models.BooleanField(default=False)),
                ('has_games', models.BooleanField(default=False)),
                ('java_support', models.BooleanField(default=False)),
                ('form_factor', models.CharField(blank=True, max_length=20, null=True)),
                ('ringtones', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='products.product')),
            ],
        ),
    ]
