# Generated by Django 5.2.5 on 2025-10-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_phonespecs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonespecs',
            name='release_year',
        ),
        migrations.AddField(
            model_name='product',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
